### ISSUE TITLE
IIBAN Support

### ISSUE THREAD

**Issue by terahlunah** [Elinvynia/schwifty#1]
Hey! Would you be interested in supporting the _IIBAN standard_ ?

It's a superset of the _IBAN standard_ adding virtual country `AA - Internet`
You can find more info on the standard here [https://github.com/globalcitizen/iiban](https://github.com/globalcitizen/iiban)

I can submit a PR myself if you want, I think there's only a few lines of code to add to support it.

**Comment by Elinvynia** [comment]
Thanks for the request, I'm happy to add that! Could you check the PR that I've done so correctly?

**Comment by terahlunah** [comment]
Awesome, I'm going to check :)
